# Generated by Django 3.2.5 on 2021-07-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_title', models.CharField(max_length=250, unique=True, verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('telephone_number', models.CharField(max_length=30, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=250, unique=True, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Зарплат')),
                ('first_work_date', models.DateField(verbose_name='Первый рабочий день')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_chief', to='company_employees.level', verbose_name='Уровень')),
                ('other_information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chief_othr_inf', to='company_employees.otherinformation', verbose_name='Прочая инофрмация')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_chief', to='company_employees.position', verbose_name='Должность')),
            ],
        ),
    ]
