# Generated by Django 3.2.5 on 2021-07-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_employees', '0003_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(default='Junior', max_length=250),
        ),
        migrations.AlterField(
            model_name='employer',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_chief', to='company_employees.chief', verbose_name='Начальник'),
        ),
    ]
